### ISSUE TITLE
Fjerne bruk av fuseki som database

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/fdk-dataservice-harvester#69]
- [x] Støtte ny DB 

- [x] ETL for Fuseki mot ny DB ved oppstart

- [x] Fjerne all nåværende bruk av fuseki

- [x] Lagre full modell i fuseki, som cache til bruk for sparql.

- [x] Sjekke sparql-spørringer i org-bff og report-bff, og gjennomføre potensielle endringer

**Comment by lillelars** [comment]
Dette ser ut til å fungere som forventet. Håndterer relasjonsbug i eget issue. Testet i chrome.
